# Generated by Django 5.0.3 on 2024-03-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flores',
            name='large_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
