# Generated by Django 4.2.7 on 2024-03-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('small_image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('dimension', models.CharField(max_length=20)),
                ('large_image', models.URLField()),
                ('extra_large_image', models.URLField()),
                ('service', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
