# Generated by Django 5.0.3 on 2024-03-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_flores_large_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='fechaEntrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
