# Generated by Django 4.2.7 on 2024-03-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_flores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flores',
            name='dimension',
            field=models.CharField(max_length=30),
        ),
    ]
