# Generated by Django 5.0.3 on 2024-03-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_flores_dimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_id', models.IntegerField()),
                ('display', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=10)),
            ],
        ),
    ]
