# Generated by Django 5.0.3 on 2024-03-06 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('colonia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodoPago', models.CharField(max_length=50)),
                ('indicaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('nombreInstitucion', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.clientes')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.flores')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.clientes')),
            ],
        ),
    ]
