# Generated by Django 5.0.3 on 2024-03-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_clientes_direccion_detalleorden_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
