# Generated by Django 5.0.3 on 2024-03-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_clientes_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flores',
            name='dimension',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
