# Generated by Django 5.0.3 on 2024-03-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_flores_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flores',
            name='extra_large_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
