# Generated by Django 5.0.3 on 2024-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_flores_extra_large_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flores',
            name='service',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
