# Generated by Django 5.0.3 on 2024-03-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_flores_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='total',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='colonia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='id_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.orden'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
