# Generated by Django 5.0.3 on 2024-03-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_orden_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='productos',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='productos',
            field=models.ManyToManyField(to='todo.flores'),
        ),
    ]
